### PR TITLE
Added *.fd to .gitignore to ignore make setup-gpt

### PR DESCRIPTION
**Pull request by artsinli**
.gitignore updated to include make setup-gpt files.

### CODE REVIEW

**Review by s1nisteR — APPROVED** [review]
(Ignore this comment)

**Review by s1nisteR — CHANGES_REQUESTED** [review]
Ignore my previous comment. I think the .fd files are necessary.

**Review by TretornESP — APPROVED** [review]
Awesome!

**Comment by TretornESP** [comment]
Thank you!

**Pull request merged**
